PreProcessing

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
path="/content/drive/MyDrive/ML Lab/Exp 02/FIFA - World Cup Summary.csv"
df=pd.read_csv(path)

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/ML Lab/Exp 02/FIFA - World Cup Summary.csv'

In [ ]:
df.head(22)

        CHAMPION       RUNNER UP    THIRD PLACE  TEAMS  AVG GOALS PER GAME
0        Uruguay       Argentina  United States     13                 3.6
1          Italy  Czechoslovakia        Germany     16                 4.1
2          Italy         Hungary         Brazil     15                 4.7
3        Uruguay          Brazil         Sweden     13                 4.0
4   West Germany         Hungary        Austria     16                 5.4
5         Brazil          Sweden         France     16                 3.6
6         Brazil  Czechoslovakia          Chile     16                 2.8
7        England    West Germany       Portugal     16                 2.8
8         Brazil           Italy   West Germany     16                 3.0
9   West Germany     Netherlands         Poland     16                 2.6
10     Argentina     Netherlands         Brazil     16                 2.7
11         Italy    West Germany         Poland     24                 2.8
12     Argentina    West Germany         France     24                 2.5
13  West Germany       Argentina          Italy     24                 2.2
14        Brazil           Italy         Sweden     24                 2.7
15        France          Brazil        Croatia     32                 2.7
16        Brazil         Germany         Turkey     32                 2.5
17         Italy          France        Germany     32                 2.3
18         Spain     Netherlands        Germany     32                 2.3
19       Germany       Argentina    Netherlands     32                 2.7
20        France         Croatia        Belgium     32                 2.6
21     Argentina          France        Croatia     32                 2.7

Drop Unneceary Features

In [ ]:
df=df.drop(columns=['YEAR','HOST','MATCHES PLAYED','GOALS SCORED'])

Handling Non-Numeric Data

In [ ]:
from sklearn.preprocessing import OneHotEncoder

encoder=OneHotEncoder(sparse_output=False)
encoded=encoder.fit_transform(df[['CHAMPION','RUNNER UP','THIRD PLACE']])
encoded_df=pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(['CHAMPION','RUNNER UP','THIRD PLACE'])
)

Handling Missing Imperator

In [ ]:
#No Missing Data

Normalization

In [ ]:
col = 'TEAMS'
df[col] = (df[col] - df[col].min()) / (df[col].max() - df[col].min())
df.head(22)

        CHAMPION       RUNNER UP    THIRD PLACE     TEAMS  AVG GOALS PER GAME
0        Uruguay       Argentina  United States  0.000000                 3.6
1          Italy  Czechoslovakia        Germany  0.157895                 4.1
2          Italy         Hungary         Brazil  0.105263                 4.7
3        Uruguay          Brazil         Sweden  0.000000                 4.0
4   West Germany         Hungary        Austria  0.157895                 5.4
5         Brazil          Sweden         France  0.157895                 3.6
6         Brazil  Czechoslovakia          Chile  0.157895                 2.8
7        England    West Germany       Portugal  0.157895                 2.8
8         Brazil           Italy   West Germany  0.157895                 3.0
9   West Germany     Netherlands         Poland  0.157895                 2.6
10     Argentina     Netherlands         Brazil  0.157895                 2.7
11         Italy    West Germany         Poland  0.578947                 2.8
12     Argentina    West Germany         France  0.578947                 2.5
13  West Germany       Argentina          Italy  0.578947                 2.2
14        Brazil           Italy         Sweden  0.578947                 2.7
15        France          Brazil        Croatia  1.000000                 2.7
16        Brazil         Germany         Turkey  1.000000                 2.5
17         Italy          France        Germany  1.000000                 2.3
18         Spain     Netherlands        Germany  1.000000                 2.3
19       Germany       Argentina    Netherlands  1.000000                 2.7
20        France         Croatia        Belgium  1.000000                 2.6
21     Argentina          France        Croatia  1.000000                 2.7